version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - HDFS_CONF_dfs_replication=1
      - HADOOP_HEAPSIZE=256
      - HADOOP_OPTS=-Xms128m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 4096
    volumes:
      - namenode-data:/hadoop/dfs/name
    ports:
      - "9870:9870" # Web UI
      - "9000:9000" # HDFS RPC

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_HEAPSIZE=256
      - HADOOP_OPTS=-Xms128m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc: 4096
    volumes:
      - datanode-data:/hadoop/dfs/data
    ports:
      - "9864:9864" # DataNode Web UI
    depends_on:
      - namenode

volumes:
  namenode-data:
  datanode-data:
